version: "3.7"
networks:
  default:
    external:
      name: nat
services:
  dockergithubselfhostedrunner:
    container_name: githubrunner
    build:
      context: .
      dockerfile: Dockerfile
    image: githubrunner:latest
    env_file: actions.env
